import os

from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from .config import settings

_STATUS_LABEL = {
    "supported": "SUPPORTED",
    "conflicting": "CONFLICTING",
    "unsupported": "UNSUPPORTED / HELD",
    "uncertain": "UNCERTAIN",
}


def build_report_pdf(report_out, suffix: str = "") -> str:
    os.makedirs(settings.reports_dir, exist_ok=True)
    name = f"report_event_{report_out.event_id}{('_' + suffix) if suffix else ''}.pdf"
    path = os.path.join(settings.reports_dir, name)

    styles = getSampleStyleSheet()
    h = ParagraphStyle("h", parent=styles["Heading1"], fontSize=15, spaceAfter=4)
    sub = ParagraphStyle("sub", parent=styles["Normal"], fontSize=9, textColor="#555555", spaceAfter=10)
    sec = ParagraphStyle("sec", parent=styles["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4)
    claim = ParagraphStyle("claim", parent=styles["Normal"], fontSize=10, spaceAfter=1, alignment=TA_LEFT)
    meta = ParagraphStyle("meta", parent=styles["Normal"], fontSize=8, textColor="#666666", spaceAfter=1)
    note = ParagraphStyle("note", parent=styles["Normal"], fontSize=8, textColor="#8a4b00", leftIndent=10, spaceAfter=1)
    ev = ParagraphStyle("ev", parent=styles["Normal"], fontSize=8, textColor="#333333", spaceAfter=6)

    doc = SimpleDocTemplate(path, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm)
    flow = [Paragraph(report_out.title, h),
            Paragraph(f"{report_out.program} &nbsp;|&nbsp; {report_out.period} &nbsp;|&nbsp; status: <b>{report_out.status.upper()}</b>", sub)]

    flow.append(Paragraph("Claims", sec))
    for c in report_out.claims:
        flow.append(Paragraph(f"<b>[{_STATUS_LABEL.get(c.status, c.status)}]</b> {c.text}", claim))
        bits = []
        if c.value:
            bits.append(f"value: {c.value}")
        if c.unit:
            bits.append(f"unit: {c.unit}")
        if c.period:
            bits.append(f"period: {c.period}")
        bits.append("evidence: " + (", ".join(f"#{i}" for i in c.evidence_ids) or "none"))
        flow.append(Paragraph(" &nbsp;|&nbsp; ".join(bits), meta))
        flow.append(Paragraph(f"<i>why:</i> {c.reasoning}", meta))
        for a in c.annotations:
            flow.append(Paragraph(f"officer note: {a.note}", note))

    kept = [s for s in report_out.suggestions if s.officer_validated == "kept"]
    if kept:
        flow.append(Paragraph("Open questions for the partner (validated)", sec))
        flow.append(ListFlowable([ListItem(Paragraph(s.question, claim)) for s in kept], bulletType="bullet"))

    flow.append(Paragraph("Evidence appendix (verbatim source records)", sec))
    for e in report_out.evidence:
        tag = " [SIMULATED]" if e.simulated else ""
        flow.append(Paragraph(f"<b>#{e.id} - {e.role} / {e.format}{tag}</b>", meta))
        flow.append(Paragraph(e.excerpt, ev))

    flow.append(Spacer(1, 8))
    flow.append(Paragraph("Generated by the evidence-based reporting agent. Every claim above cites the evidence record(s) behind it.", sub))
    doc.build(flow)
    return path
